name: zapzap
base: core22
version: '0.0.0'   # será substituída pelo CI usando sed ou variável de ambiente
summary: Zapzap WhatsApp client web app
description: |
  Zapzap é um cliente WhatsApp para desktop baseado em PyQt6.

grade: stable
confinement: strict

apps:
  zapzap:
    command: zapzap

parts:
  zapzap:
    plugin: python
    source: .
    python-packages:
      - PyQt6
      - PyQt6-WebEngine
      - dbus-python
    build-packages:
      - python3-dev
      - python3-dbus
      - build-essential
