name: Build and Release Zapzap

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.13'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build stdeb

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build wheel
        run: python -m build --wheel --outdir dist

      - name: Build .deb package
        run: |
          pip install .
          python3 -m stdeb.command.bdist_deb

      - name: Upload wheel to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.whl
          asset_name: zapzap-${{ env.VERSION }}.whl
          asset_content_type: application/octet-stream

      - name: Upload .deb to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: deb_dist/*.deb
          asset_name: zapzap-${{ env.VERSION }}.deb
          asset_content_type: application/vnd.debian.binary-package
