name: Build and Release Zapzap

on:
  release:
    types: [created]  # Dispara quando uma release é criada

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.13'

    steps:
      # 1️⃣ Pegar o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 3️⃣ Instalar ferramentas de build
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build stdeb

      # 4️⃣ Obter versão da tag
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # 5️⃣ Build do wheel
      - name: Build wheel
        run: python -m build --wheel --outdir dist

      # 6️⃣ Build do .deb
      - name: Build .deb package
        run: |
          pip install .
          python3 -m stdeb.command.bdist_deb --dist-dir dist

      # 7️⃣ Conferir arquivos gerados
      - name: List dist folder
        run: ls -l dist/

      # 8️⃣ Criar release no GitHub
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
